-- V1: Criação das tabelas base (Oracle 12c+ com IDENTITY).
-- Objetivo: disponibilizar o esquema inicial do banco.

-- FILIAL
CREATE TABLE IF NOT EXISTS TB_FILIAL (
                                         ID_FILIAL         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                         NM_FILIAL         VARCHAR(255) NOT NULL,
    DS_ENDERECO       VARCHAR(255),
    DS_BAIRRO         VARCHAR(255),
    NR_CEP            VARCHAR(255),
    DS_CIDADE         VARCHAR(255),
    DS_ESTADO         VARCHAR(255),
    VL_LATITUDE       DOUBLE PRECISION,
    VL_LONGITUDE      DOUBLE PRECISION,
    RAIO_GEOFENCE_M   DOUBLE PRECISION
    );

-- MOTO
CREATE TABLE IF NOT EXISTS TB_MOTO (
                                       ID_MOTO       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                       NR_ANO        INTEGER CHECK (NR_ANO >= 2000),
    DT_CRIACAO    TIMESTAMP(6),
    DS_MARCA      VARCHAR(255),
    DS_MODELO     VARCHAR(255),
    CD_PLACA      VARCHAR(255) NOT NULL UNIQUE,
    DS_STATUS     VARCHAR(255),
    VL_LATITUDE   DOUBLE PRECISION,
    VL_LONGITUDE  DOUBLE PRECISION,
    ID_FILIAL     BIGINT,
    CONSTRAINT FK_MOTO_FILIAL
    FOREIGN KEY (ID_FILIAL) REFERENCES TB_FILIAL (ID_FILIAL)
    );

-- AGENDAMENTO
CREATE TABLE IF NOT EXISTS TB_AGENDAMENTO (
                                              ID_AGENDAMENTO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                              DT_AGENDADA    TIMESTAMP(6) NOT NULL,
    DT_CRIACAO     TIMESTAMP(6),
    DS_DESCRICAO   VARCHAR(255) NOT NULL,
    ID_MOTO        BIGINT NOT NULL,
    CONSTRAINT FK_AGENDAMENTO_MOTO
    FOREIGN KEY (ID_MOTO) REFERENCES TB_MOTO (ID_MOTO)
    );

-- EVENTO
CREATE TABLE IF NOT EXISTS TB_EVENTO (
                                         ID_EVENTO       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                         DT_HR_EVENTO    TIMESTAMP(6) NOT NULL,
    DS_LOCALIZACAO  VARCHAR(255),
    DS_MOTIVO       VARCHAR(255) NOT NULL,
    TP_EVENTO       VARCHAR(255) NOT NULL,
    ID_MOTO         BIGINT NOT NULL,
    CONSTRAINT FK_EVENTO_MOTO
    FOREIGN KEY (ID_MOTO) REFERENCES TB_MOTO (ID_MOTO)
    );

-- USUARIO
CREATE TABLE IF NOT EXISTS TB_USUARIO (
                                          ID_USUARIO  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                          DS_EMAIL    VARCHAR(255) NOT NULL UNIQUE,
    NM_USUARIO  VARCHAR(255) NOT NULL,
    TP_PERFIL   VARCHAR(255) NOT NULL,
    DS_SENHA    VARCHAR(255) NOT NULL,
    ID_FILIAL   BIGINT,
    CONSTRAINT FK_USUARIO_FILIAL
    FOREIGN KEY (ID_FILIAL) REFERENCES TB_FILIAL (ID_FILIAL)
    );